In [1]:
import numpy as np
np.array([1,2,3,4], dtype='uint32')

array([1, 2, 3, 4], dtype=uint32)

In [2]:
2**16

65536

In [3]:
2**32


4294967296

In [5]:
a = np.array([5,4,3,2,1])

In [9]:
np.take(a, [1,2])

array([4, 3])

In [10]:
np2d = np.array([np.array([1,2,3]), np.array([1,2,3])])

In [13]:
np.take(np2d, [0,1])

array([1, 2])

In [16]:
np2d[[0,0,1]]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])